# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
#ssh -gNR 3000:localhost:3000 www.fluidtickets.com -l root

# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.
# should now be pushed to prod server - touch

development:
  api_key: f542c9738802d1d4b83830c83e1fa2f4
  secret_key: b3dd3fb523da94924849989502fa6598
  canvas_page_name: http://facebooker-authlogic-bridge.heroku.com
  callback_url: http://facebooker-authlogic-bridge.heroku.com
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 3000
    local_port: 3000
    server_alive_interval: 0

test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
      api_key: f542c9738802d1d4b83830c83e1fa2f4
      secret_key: b3dd3fb523da94924849989502fa6598
      canvas_page_name: http://facebooker-authlogic-bridge.heroku.com
      callback_url: http://facebooker-authlogic-bridge.heroku.com
      pretty_errors: true
      set_asset_host_to_callback_url: true
      tunnel:
        public_host_username: 
        public_host: 
        public_port: 3000
        local_port: 3000
        server_alive_interval: 0
